### ISSUE TITLE
Refactoring quality app

### ISSUE THREAD

**Issue by jokiefer** [mrmap-community/mrmap#129]
### Proposed Changes
1. change the model dependencies from `service` to `resourceNew`.
2. use model mixins `CommonInfo`, `GenericModelMixin` if needed. `GenericModelMixin` to serve urls for model instances `CommonInfo` for model instances which shall be restricted by the django-guardian permission system.
3. refactor quality models: remove uuidpk from models if not needed. We use uuid pk's only for models which are externaly accessable.
4. move managers from `models.py` to `managers.py`
5. add action button(s) to all table views to start the quality check task
6. use `NewJob` and `CurrentTask` `Task` classes to show task progress in the gui

### Justification
* `service` app is deprecated. New `resourceNew` app shall be used.
* managers shall be separated from models

**Comment by Unraveler** [comment]
TODOs:
---

- [ ]  Validation of other resource types (WMS / WFS/  CSW), Layer,  Feature Types and other metadata types (at the moment only validating DataSet Metadata)

- [ ]  Instead of validating through `origin_url` , the validation needs to through the document in Mr Map (`resourceNew.models.Document`) [**Is there a relation between document and data to validate?**]

- [ ]  Check all TODOS and confirm with @jokiefer , that all the changes made are the desired

- [ ]  See validation status in the table with an icon (like a traffic sign with lights) #130

**Comment by MrSnyder** [comment]
Updated @Unraveler's  TODOs:

- Striked through those that are part of other tickets, so we can finally finish this one
- Remark on the source of the document to be validated: As discussed with @jokiefer  and @armin11: the ETF validator should fetch it itself from MrMap's XML resource endpoints
